#!/bin/sh

### BEGIN INIT INFO
# Provides:			photon
# Required-Start:	$local_fs $syslog
# Required-Stop:	$local_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:starts photon geocoder
# Description:		starts photon geocoder using start-stop-daemon
### END INIT INFO

LOGFILE="/var/log/photon.log"
JAVA=$(which java)
PHOTON_DIR="/var/www/photon"
PHOTON_BIN="photon.jar"
PHOTON_DATA="$PHOTON_DIR"
USER="www-data"
GROUP="www-data"
DESC="Photon"
NAME="photon"
COMMAND="-jar $PHOTON_DIR/$PHOTON_BIN"
set -e

. /lib/lsb/init-functions

start() {
	echo "Starting $DESC... "
	start-stop-daemon --start --background --chuid "$USER:$GROUP" --chdir "$PHOTON_DIR" --make-pidfile --pidfile /var/run/$NAME.pid --verbose --startas $JAVA -- $COMMAND
	echo "done"
}

#We need this function to ensure the whole process tree will be killed
killtree() {
	local _pid=$1
	local _sig=${2-TERM}
	for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
		killtree ${_child} ${_sig}
	done
	kill -${_sig} ${_pid}
}

stop() {
	echo "Stopping $DESC... "
	while test -d /proc/$(cat /var/run/$NAME.pid); do
		killtree $(cat /var/run/$NAME.pid) 15
		sleep 0.5
	done
	rm /var/run/$NAME.pid
	echo "done"
}

status() {
	status_of_proc -p /var/run/$NAME.pid "" "$DESC" && exit 0 || exit $?
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	status)
		status
		;;
	*)
		echo "Usage: $NAME {start|stop|restart|status}" >&2
		exit 1
		;;
esac

exit 0